import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by crate next app" />
        <link rel="icon" href='/favicon.ico' />
      </Head>

      <main>
        <h1>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid perferendis cum odio tenetur voluptatibus consectetur harum, asperiores eligendi deleniti quam nulla, hic exercitationem dolorum dolorem sapiente itaque possimus esse. Quo architecto quis quas? Quisquam voluptates in facere nihil dolorem nostrum?
        </p>
      </main>
    </>
  )
}

export default Home